//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web29Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Tour
    {
        public int ID { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> tour_id { get; set; }
        public string data { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    
        public virtual Tour Tour { get; set; }
        public virtual User User { get; set; }
    }
}
