//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web29Api.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Comment_Tour = new HashSet<Comment_Tour>();
        }
    
        public int ID { get; set; }
        public string name_tour { get; set; }
        public string description { get; set; }
        public string thumbnail { get; set; }
        public string location { get; set; }
      
        public Nullable<decimal> price_tour { get; set; }
        public string total_time { get; set; }
        public string category_tour { get; set; }
        public Nullable<bool> status { get; set; }
        public System.DateTime created_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Tour> Comment_Tour { get; set; }
        public object ActualHydPressureDropPipe { get; internal set; }
    }
}
